version: '3.8'

services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - lenet

  db:
    image: postgres:13
    container_name: db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lenet

volumes:
  postgres_data:

networks:
  lenet:
    driver: bridge
